In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('online_retail_II.csv')

In [3]:
df.shape

(47114, 8)

In [4]:
df.isna().sum()

Invoice            0
StockCode          0
Description      262
Quantity           1
InvoiceDate        1
Price              1
Customer ID    13522
Country            1
dtype: int64

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 47114 entries, 0 to 47113
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Invoice      47114 non-null  object
 1   StockCode    47114 non-null  object
 2   Description  46852 non-null  object
 3   Quantity     47113 non-null  float64
 4   InvoiceDate  47113 non-null  object
 5   Price        47113 non-null  float64
 6   Customer ID  33592 non-null  float64
 7   Country      47113 non-null  object
dtypes: float64(3), object(5)
memory usage: 2.9+ MB

In [6]:
df.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12.0,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12.0,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12.0,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48.0,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24.0,2009-12-01 07:45:00,1.25,13085.0,United Kingdom

In [7]:
df.describe()

           Quantity         Price   Customer ID
count  47113.000000  47113.000000  33592.000000
mean       9.508289      4.335300  15465.050548
std       60.201466     21.233927   1665.783870
min    -1395.000000      0.000000  12346.000000
25%        1.000000      1.250000  14087.000000
50%        2.000000      2.570000  15499.000000
75%        8.000000      4.950000  16918.000000
max     5184.000000   1998.490000  18287.000000

In [8]:
df["InvoiceDate"] = pd.to_datetime(df["InvoiceDate"], errors="coerce")

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 47114 entries, 0 to 47113
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Invoice      47114 non-null  object
 1   StockCode    47114 non-null  object
 2   Description  46852 non-null  object
 3   Quantity     47113 non-null  float64
 4   InvoiceDate  47113 non-null  datetime64[ns]
 5   Price        47113 non-null  float64
 6   Customer ID  33592 non-null  float64
 7   Country      47113 non-null  object
dtypes: datetime64[ns](1), float64(3), object(4)
memory usage: 2.9+ MB

In [10]:
(df["Quantity"] < 0).sum()

np.int64(1166)

In [11]:
(df["Price"] < 0).sum()

np.int64(0)

In [12]:
df[df["Quantity"] == -4200][["Invoice", "Quantity", "Price", "Customer ID"]]

Empty DataFrame
Columns: [Invoice, Quantity, Price, Customer ID]
Index: []

In [13]:
df[(df["Price"] == 0) & (df["Quantity"] < 0)].shape

(96, 8)

In [14]:
df[(df["Price"] == 0) & (df["Quantity"] < 0)].shape

(96, 8)

In [15]:
df = df[~((df["Price"] == 0) & (df["Quantity"] < 0))]

In [16]:
df.shape

(47018, 8)

In [17]:
df.isna().sum()

Invoice            0
StockCode          0
Description      186
Quantity           1
InvoiceDate        1
Price              1
Customer ID    13426
Country            1
dtype: int64

In [18]:
df.duplicated().sum()

np.int64(524)

In [19]:
df.drop_duplicates(inplace=True)

In [20]:
df.shape

(46494, 8)

In [21]:
df.isnull().sum()

Invoice            0
StockCode          0
Description      186
Quantity           1
InvoiceDate        1
Price              1
Customer ID    13404
Country            1
dtype: int64

In [22]:
(df["Price"] == 0).sum()

np.int64(194)

In [23]:
df[df["Price"] == 0][["Invoice", "StockCode", "Description", "Quantity", "Price", "Customer ID"]].sample(20)

      Invoice StockCode Description  Quantity  Price  Customer ID
43629  493169     72777         NaN      14.0    0.0          NaN
43782  493193    35977B         NaN       7.0    0.0          NaN
43627  493167     22330         NaN     174.0    0.0          NaN
43800  493198     20887         NaN       6.0    0.0          NaN
43578  493143     20736         NaN     187.0    0.0          NaN
43587  493153    35603B         NaN      12.0    0.0          NaN
44502  493285    79309A         NaN       1.0    0.0          NaN
21852  491117     20879         NaN      12.0    0.0          NaN
43829  493227    84558B         NaN       4.0    0.0          NaN
14503  490543     37446         NaN     222.0    0.0          NaN
44501  493279    72803B         NaN       3.0    0.0          NaN
42011  492835     22187         NaN      48.0    0.0          NaN
43585  493149    17164D         NaN     784.0    0.0          NaN
43636  493175     85151         NaN      12.0    0.0          NaN
43628  493166     22390         NaN      15.0    0.0          NaN
43590  493156     79163         NaN    2000.0    0.0          NaN
45737  493530    84877C         NaN       1.0    0.0          NaN
15489  490688     21133         NaN     270.0    0.0          NaN
43821  493219     20995         NaN       3.0    0.0          NaN
43831  493230     21915         NaN       1.0    0.0          NaN

In [24]:
df[df["Price"] == 0]["Customer ID"].notna().sum()

np.int64(7)

In [25]:
df[df["Price"] == 0]["Description"].notna().sum()

np.int64(9)

# Removed zero-priced transactions as they do not contribute
# to meaningful revenue analysis or demand forecasting.

In [26]:
df = df[df["Price"] > 0]

In [27]:
df.shape

(46299, 8)

In [28]:
df.isna().sum()

Invoice            0
StockCode          0
Description        0
Quantity           0
InvoiceDate        0
Price              0
Customer ID    13216
Country            0
dtype: int64

In [29]:
(df["Quantity"] < 0).sum()

np.int64(1068)

In [30]:
df[df["Quantity"] < 0].head(20)

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
178,C489449,22087,PAPER BUNTING WHITE LACE,-12.0,2009-12-01 10:33:00,2.95,16321.0,Australia
179,C489449,85206A,CREAM FELT EASTER EGG BASKET,-6.0,2009-12-01 10:33:00,1.65,16321.0,Australia
180,C489449,21895,POTTING SHED SOW 'N' GROW SET,-4.0,2009-12-01 10:33:00,4.25,16321.0,Australia
181,C489449,21896,POTTING SHED TWINE,-6.0,2009-12-01 10:33:00,2.10,16321.0,Australia
182,C489449,22083,PAPER CHAIN KIT RETRO SPOT,-12.0,2009-12-01 10:33:00,2.95,16321.0,Australia
183,C489449,21871,SAVE THE PLANET MUG,-12.0,2009-12-01 10:33:00,1.25,16321.0,Australia
184,C489449,84946,ANTIQUE SILVER TEA GLASS ETCHED,-12.0,2009-12-01 10:33:00,1.25,16321.0,Australia
185,C489449,84970S,HANGING HEART ZINC T-LIGHT HOLDER,-24.0,2009-12-01 10:33:00,0.85,16321.0,Australia
186,C489449,22090,PAPER BUNTING RETRO SPOTS,-12.0,2009-12-01 10:33:00,2.95,16321.0,Australia
196,C489459,90200A,PURPLE SWEETHEART BRACELET,-3.0,2009-12-01 10:44:00,4.25,17592.0,United Kingdom
197,C489459,90200D,PINK SWEETHEART BRACELET,-3.0,2009-12-01 10:44:00,4.25,17592.0,United Kingdom
198,C489459,90200B,BLACK SWEETHEART BRACELET,-3.0,2009-12-01 10:44:00,4.25,17592.0,United Kingdom
199,C489459,90200E,GREEN SWEETHEART BRACELET,-3.0,2009-12-01 10:44:00,4.25,17592.0,United Kingdom
200,C489459,90200C,BLUE SWEETHEART BRACELET,-3.0,2009-12-01 10:44:00,4.25,17592.0,United Kingdom
201,C489459,90185C,BLACK DIAMANTE EXPANDABLE RING,-3.0,2009-12-01 10:44:00,4.25,17592.0,United Kingdom
202,C489459,90185B,AMETHYST DIAMANTE EXPANDABLE RING,-3.0,2009-12-01 10:44:00,4.25,17592.0,United Kingdom
203,C489459,90003C,MIDNIGHT BLUE PAIR HEART HAIR SLIDE,-3.0,2009-12-01 10:44:00,3.75,17592.0,United Kingdom
204,C489459,90003D,CRYSTAL PAIR HEART HAIR SLIDES,-3.0,2009-12-01 10:44:00,3.75,17592.0,United Kingdom
205,C489459,90003B,ROSE COLOUR PAIR HEART HAIR SLIDES,-3.0,2009-12-01 10:44:00,3.75,17592.0,United Kingdom
206,C489459,90209C,PINK ENAMEL+GLASS HAIR COMB,-3.0,2009-12-01 10:44:00,2.10,17592.0,United Kingdom

In [32]:
df.to_csv("cleaned_retail.csv", index=False)